version: '3.5'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - postgres_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg-data:

networks:
  postgres_network:
    external: true

# vim: tabstop=2 shiftwidth=2 expandtab
